spring:
  datasource:
    # H2是一个Java编写的关系型数据库，它可以被嵌入Java应用程序中使用，或者作为一个单独的数据库服务器运行。它支持标准的sql和jdbc，基于内存存储，适用于测试
    # driver-class-name: org.h2.Driver
    # schema: classpath:db/schema-h2.sql
    # data: classpath:db/data-h2.sql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smart-app?useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=GMT%2B8
    username: root
    password: admin123
  redis:
    host: 192.168.163.11
    port: 63791
    password: q@#WE@190
    database: 4
    jedis:
      pool:
        max-active: 10
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

server:
  port: 8088
logging:
  level:
    root: info
    com.smart.smartapp: debug
  file:
    path: ./logs
